# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

name: PyLint the codebase

# trigger event is a push to the main repo branch (or a manual launch)
on:
  workflow_dispatch:
  push:
    branches:
    - main

# job definitions
jobs:
  run_pylint:
    name: Execute pylint

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Pylint the codebase
        run: |
          pylint --rcfile=.pylintrc --recursive=y ./
